# Generated by Django 4.1.6 on 2023-02-27 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_for_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription',
            field=models.ForeignKey(default='basic', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='image_for_users.memberships'),
        ),
    ]
